[package]
name = "node_runtime"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/node_runtime.rs"
doctest = false

[dependencies]
anyhow.workspace = true
archive.workspace = true
async-trait.workspace = true
futures.workspace = true
log.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true
util.workspace = true
windows.workspace = true
